### ISSUE TITLE
大佬，能不能弄个java版本？

### ISSUE THREAD

**Issue by YuPf1989** [Hankkin/PageLayoutDemo#2]
RT

**Comment by Hankkin** [comment]
晚上回去搞一个 晚上来看吧

**Comment by VliceZ** [comment]
同求java版本

**Comment by Hankkin** [comment]
java版本已上传
https://github.com/Hankkin/PageLayoutDemojava

**Comment by YuPf1989** [comment]
谢谢大佬，另外发现了一个问题，如果不设置customview的话，项目会直接报空指针，建议做个判空，毕竟loading，error,empty都有默认的布局

**Comment by Hankkin** [comment]
好了 已经提交更新了 感谢提issues 建议还是看Kotlin版本 比如Kotlin中的可空类型和非空类型刚才的NullPointException就不会报错了  Java版本写的比较急代码健壮性较差
